apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc # This name MUST match the claimName in the CronJob
spec:
  accessModes:
    - ReadWriteOnce # Or ReadWriteMany, depending on your needs
  resources:
    requests:
      storage: 1Gi # Adjust the size as needed